name: Update Problem Count Badge

on:
  push:
    paths:
      - 'C++/*.cpp'
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Count .cpp files and update badge
        run: |
          count=$(ls C++/*.cpp | wc -l)
          echo "Found $count cpp files"

          # Update badge number
          if sed --version 2>/dev/null; then
            sed -i -E "s/Problems%20Solved-[0-9]+-success/Problems%20Solved-$count-success/" README.md
          else
            sed -i '' -E "s/Problems%20Solved-[0-9]+-success/Problems%20Solved-$count-success/" README.md
          fi

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update problem count badge" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
